### ISSUE TITLE
Using of deprecated UIWebView API

### ISSUE THREAD

**Issue by va1da** [SRGSSR/srgletterbox-apple#209]
In the latest version of SRGLetterbox-apple most of the frameworks are still actively using UIWebView which is deprecated and could be removed by Apple at any time.

Is it possible for to adapt your framework to this change?

Thanks,
Ondřej

**Comment by defagos** [comment]
Ondřej,

That is odd, we aren’t using `UIWebView` at all directly in Letterbox or any of our in-house dependencies.

I’ll check the linker flags and 3rd party dependencies. We have scheduled a release for the end of the week / beginning of next week, so this is definitely something we can try to fix before.

**Comment by va1da** [comment]
I ran this in my project file:
![Screenshot 2020-03-03 at 14 14 34](https://user-images.githubusercontent.com/961352/75779122-5ce1dd00-5d59-11ea-9735-8d46c2a196c8.png)

**Comment by defagos** [comment]
The comScore 6.0 dependency references `UIWebView`, which is why you experience this issue. Luckily, the comScore library is in version 6.2 now and the issue was fixed in 6.1. So we can fix the problem right away.

As I said above, we are planning a Letterbox release for the end of the week / beginning of next week. The fix will definitely be part of it. I see you are using Letterbox 2.0.0, the next update will be a 3.0.0. We had a minor breaking API change which should not affect you, so the update should be painless without any code change required.

I see you intend to deliver your app update by the end of March. The question is therefore: Do you need the release to happen tomorrow or could you wait until Friday / next Monday

**Comment by va1da** [comment]
Hi,
thanks a lot for a quick reply.
This Friday/next Monday is OK for us.

**Comment by defagos** [comment]
Thanks for the info. I could successfully update the comScore library. The fix will definitely be delivered as part of Letterbox 3.0.0 in the upcoming days.

**Comment by va1da** [comment]
Regarding comScore: we are experiencing a lot of crashes like this in our app because of ComScore, could somehow check if the newest update has this fixed?

`EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x6a.
  ?, in ComScore::Configuration::removeListener(ComScore::ConfigurationListener*)
  ?, in ComScore::Core::~Core()
  ?, in ComScore::ReferrerTasksThread<ComScore::Core>::run()
  ?, in ComScore::Thread::threadEntryPoint()
  ?, in threadEntryProc
...
(1 additional frame(s) were not displayed)`

Thanks

**Comment by defagos** [comment]
I checked AppCenter crash reports. We have only 15 related crashes on Play SRF 2.9.7 in 2 months. Play SRF has a large user base, so I am puzzled by the fact you experienced lots of crashes in your app. How much is "a lot" in your case?

I see there is a crash fix related to notifications [mentioned in 6.1.0 release notes](https://github.com/comScore/ComScore-iOS-watchOS-tvOS/blob/e3e2871afc84a927c6c066487112d8ec4b3256ad/CHANGELOG.pdf). But I cannot say whether this is related to this listener issue or not.

**Comment by defagos** [comment]
@va1da I closed this issue since the corresponding fix has been delivered. About the crashes you experience, I propose we discuss the matter further on a dedicated [SRGAnalytics issue](https://github.com/SRGSSR/srganalytics-apple/issues/38).
