### ISSUE TITLE
Icons letting the user jump forward or backward in a segmented video are not visible on iPhone

### ISSUE THREAD

**Issue by TorstenKaufmann** [SRGSSR/srgletterbox-apple#235]
### Issue type
Bug?

Incorrect behavior
The icons letting the user jump forward or backwards a few seconds are not shown if
- the timeline is shown
- the device is in portrait mode
- the functionality itself is still present 
 
Feature request
- bring back the icons or disable jumping feature

### Description of the problem

It might be a layout issue with videos providing segments and the client of SRGLetterbox  not resizing the view correctly.

### Environment information
* Library version: 6.0.0
* iOS all, iOS 12 - 14
* Device: iPhone

### Reproducibility
Always reproducible

### Github
https://github.com/mmz-srf/SRFMediaPlayer-iOS

**Expected**
![image](https://user-images.githubusercontent.com/861652/99485659-2b4e8780-2963-11eb-9dc0-148f8f533369.png)

**Current**
![image](https://user-images.githubusercontent.com/861652/99485713-491bec80-2963-11eb-8696-80e906d5ef44.png)

**Interface Builder iPhone**

<img width="1186" alt="Screenshot 2020-11-18 at 06 23 11" src="https://user-images.githubusercontent.com/861652/99487449-acf3e480-2966-11eb-9823-b19f1a906046.png">

<img width="1245" alt="Screenshot 2020-11-18 at 06 22 53" src="https://user-images.githubusercontent.com/861652/99487462-b54c1f80-2966-11eb-96a5-02c73db4ee6a.png">

**Interface Builder iPad (Icons visible)**

<img width="1011" alt="Screenshot 2020-11-18 at 06 30 08" src="https://user-images.githubusercontent.com/861652/99487991-b0d43680-2967-11eb-82d4-ece537987440.png">

### Steps to reproduce

> Provide step-by-step instructions about how to reliably reproduce the issue (or if not possible, with a good probability)

1. Open video with segments
2. Hold phone in portrait
3. Jump forth and back without << or >> icons

**Comment by defagos** [comment]
Hi @TorstenKaufmann,

This is actually expected behavior. Our layout is responsive and we get rid of some icons depending on the width or height of the Letterbox view.

When the timeline is displayed Letterbox view namely shrinks by default. In such cases your application should adjust constraints so that more vertical space is provided when possible, most notably in portrait orientation, so that no shrinking is required. Please have a look at the corresponding [section of the getting start guide](https://github.com/SRGSSR/srgletterbox-apple/blob/master/docs/GETTING_STARTED.md#controls-and-overlays) and to our demo code.

Hope that helps, otherwise feel free to get in touch so that we can help you directly with the implementation.

Best regards.
