### ISSUE TITLE
The server SSH fingerprint failed to verify

### ISSUE THREAD

**Issue by va1da** [SRGSSR/srgletterbox-apple#239]
Hi,
I'm trying to use new letterbox library thru Swift Package Manager, but it gives me this error:
![Screenshot 2020-12-29 at 14 44 54](https://user-images.githubusercontent.com/961352/103289064-9c636f00-49e6-11eb-86cf-7c7ffa155787.png)

Is there still a way to import Letterbox with Carthage or SPM is now only choice?
Thanks for help.

**Comment by pyby** [comment]
@va1da In the `tmp` folder, could you try `git clone https://github.com/SRGSSR/srgletterbox-apple.git` and check that clone works?

You should check your git / ssh configuration on your machine.
`~/.ssh/known_hosts` mays be the cause. https://github.com/webfactory/ssh-agent/issues/4

Since version 6.0.0, all SRGLetterbox-Apple dependencies are now on a public repository, and only available with SPM packager and Xcode 12. No SSH or https credentials required.


Then, the migration guide is available to switch from Carthage to SPM, written from various iOS team feedbacks.
https://github.com/SRGSSR/srgletterbox-apple/wiki/Migration-guides

**Comment by va1da** [comment]
`git clone https://github.com/SRGSSR/srgletterbox-apple.git` works for me.
So it must me some Xcode issue.

Adding github.com to known_hosts didn't help.

**Comment by va1da** [comment]
OK, so in case that anyone else will experience this issue: this solved my problem: https://stackoverflow.com/a/58179025/14919598

**Comment by pyby** [comment]
@va1da Thank you very much for sharing to all of us the solution, if we experience the same issue.
